-- ⚠️ OUTDATED / DO NOT USE FOR MIGRATIONS ⚠️
-- This file was an early reference schema and does NOT match the real
-- production database. It includes tables (`workouts`, `schedule`) that
-- do not actually exist in the live MariaDB instance, and is missing real
-- tables (`equipment_scan_logs`, `password_resets`, `sessions`).
--
-- Use `fordago_export_2026-08-07.sql` in this same folder instead — it
-- reflects the actual phpMyAdmin export of the live database as of Aug 7, 2026.
--
-- This file is kept only for historical reference and will be removed
-- once the Laravel migrations are written and verified.
